### ISSUE TITLE
Incorrect height calc if padding

### ISSUE THREAD

**Issue by AlphaOrange** [AlphaOrange/Orbitlist#13]
If the surrounding elements has padding > 0, the height calculation fails and orbitlist is displayed too small (also shifted left and top).

**Comment by aloisdg** [comment]
Could it be fixed with [`Box-sizing: Border-box`](https://www.paulirish.com/2012/box-sizing-border-box-ftw/)?

**Comment by AlphaOrange** [comment]
Nope, it doesn't. The docu page actually uses border-box on all elements.
The problem is js uses the inner height (minus borders and padding) for calculation and the whole element (offsetting from the top left corner) for drawing.
